// Generated by scripts/exercise-art/install.py from approved.json. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

/** Approved exercise art: catalog id to its dot frames (start, end; three for a few lifts). */
export const EXERCISE_ART: Readonly<Record<string, readonly ImageSourcePropType[]>> = {
  'bundled-barbell-back-squat': [
    require('../../assets/images/exercise-art/barbell-back-squat-0.png'),
    require('../../assets/images/exercise-art/barbell-back-squat-1.png'),
  ],
};
