"""Copy approved candidates into the app and regenerate the manifest.

Usage: install.py <work-dir> <id>=c<n> [<id>=c<n> ...]
       install.py --manifest          (only rewrite the manifest from approved.json)

Records each pick in approved.json (catalog id -> frame count), copies the frames from
<work-dir>/frames to mobile/assets/images/exercise-art/<slug>-<i>.png and writes
src/device/exercise-art.generated.ts. Only lifts Marvin approved go in.
"""
import json, os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOBILE = os.path.normpath(os.path.join(HERE, "..", ".."))
ASSETS = os.path.join(MOBILE, "assets", "images", "exercise-art")
APPROVED = os.path.join(HERE, "approved.json")
MANIFEST = os.path.join(MOBILE, "src", "device", "exercise-art.generated.ts")

approved = json.load(open(APPROVED)) if os.path.exists(APPROVED) else {}
lifts = {l["id"]: l for l in json.load(open(os.path.join(HERE, "lifts.json")))}
if sys.argv[1] != "--manifest":
    work = sys.argv[1]
    for pick in sys.argv[2:]:
        lift_id, cand = pick.split("=")
        assert lift_id in lifts, lift_id
        slug = lift_id.removeprefix("bundled-")
        frames = sorted(f for f in os.listdir(os.path.join(work, "frames")) if f.startswith(f"{slug}-{cand}-"))
        assert len(frames) in (2, 3), (pick, frames)
        for i, f in enumerate(frames):
            shutil.copyfile(os.path.join(work, "frames", f), os.path.join(ASSETS, f"{slug}-{i}.png"))
        approved[lift_id] = len(frames)
    with open(APPROVED, "w") as f:
        json.dump(dict(sorted(approved.items())), f, indent=1)
        f.write("\n")

lines = [
    "// Generated by scripts/exercise-art/install.py from approved.json. Do not edit by hand.",
    "import type { ImageSourcePropType } from 'react-native';",
    "",
    "/** Approved exercise art: catalog id to its dot frames (start, end; three for a few lifts). */",
    "export const EXERCISE_ART: Readonly<Record<string, readonly ImageSourcePropType[]>> = {",
]
for lift_id, count in sorted(approved.items(), key=lambda kv: list(lifts).index(kv[0])):
    slug = lift_id.removeprefix("bundled-")
    lines.append(f"  '{lift_id}': [")
    lines += [f"    require('../../assets/images/exercise-art/{slug}-{i}.png')," for i in range(count)]
    lines.append("  ],")
lines += ["};", ""]
open(MANIFEST, "w").write("\n".join(lines))
print(f"{len(approved)} lifts in the manifest")
