"""Copy approved candidates into the app and regenerate the manifest.

Usage: install.py <work-dir> <id>=c<n> [<id>=c<n> ...]
       install.py --manifest          (only rewrite the manifest from approved.json)

Records each pick in approved.json (catalog id -> frame count), copies the frames from
<work-dir>/frames to mobile/assets/images/exercise-art/<slug>-<i>.png and writes
src/device/exercise-art.generated.ts. Only lifts Marvin approved go in.

Every run also rebuilds the picker thumbnails in mobile/assets/images/exercise-art/thumbs/: each
lift's last (working) frame cropped square around the figure at 3x the picker tile, plus
`_empty.png`, the bare dot grid for rows without art.
"""
import json, os, shutil, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
MOBILE = os.path.normpath(os.path.join(HERE, "..", ".."))
ASSETS = os.path.join(MOBILE, "assets", "images", "exercise-art")
APPROVED = os.path.join(HERE, "approved.json")
MANIFEST = os.path.join(MOBILE, "src", "device", "exercise-art.generated.ts")
THUMBS = os.path.join(ASSETS, "thumbs")
THUMB_PX = 156  # the picker tile (plansGeometry.artTile, 52 pt) at 3x
PITCH = 9  # dots.py's dot pitch in px
LIT = 160  # alpha above this is a lit dot; the off grid sits below it
MIN_SIDE = 56 * PITCH  # small figures don't blow up past the others


def thumb(frame_path, out_path):
    """The working frame cropped square around its lit dots (10% margin, whole dots)."""
    im = Image.open(frame_path).convert("RGBA")
    x0, y0, x1, y1 = im.getchannel("A").point(lambda a: 255 if a > LIT else 0).getbbox()
    side = max(MIN_SIDE, round(max(x1 - x0, y1 - y0) * 1.1 / PITCH) * PITCH)
    cx, cy = (x0 + x1) // 2, (y0 + y1) // 2
    left = min(max(0, (cx - side // 2) // PITCH * PITCH), im.width - side)
    top = min(max(0, (cy - side // 2) // PITCH * PITCH), im.height - side)
    tile = im.crop((left, top, left + side, top + side)).resize((THUMB_PX, THUMB_PX), Image.LANCZOS)
    save_small(tile, out_path)


def empty_thumb(frame_path, out_path):
    """The off dot grid alone: the frame's top-left dot cell (always clear of the figure) tiled."""
    cell = Image.open(frame_path).convert("RGBA").crop((0, 0, PITCH, PITCH))
    side = 60 * PITCH
    grid = Image.new("RGBA", (side, side))
    for x in range(0, side, PITCH):
        for y in range(0, side, PITCH):
            grid.paste(cell, (x, y))
    save_small(grid.resize((THUMB_PX, THUMB_PX), Image.LANCZOS), out_path)


def save_small(im, out_path):
    """A 32-colour palette PNG: the art has four inks, so it looks the same at a fraction of the size."""
    im.quantize(32, method=Image.Quantize.FASTOCTREE).save(out_path, optimize=True)


approved = json.load(open(APPROVED)) if os.path.exists(APPROVED) else {}
lifts = {l["id"]: l for l in json.load(open(os.path.join(HERE, "lifts.json")))}
if sys.argv[1] != "--manifest":
    work = sys.argv[1]
    for pick in sys.argv[2:]:
        lift_id, cand = pick.split("=")
        assert lift_id in lifts, lift_id
        slug = lift_id.removeprefix("bundled-")
        frames = sorted(f for f in os.listdir(os.path.join(work, "frames")) if f.startswith(f"{slug}-{cand}-"))
        assert len(frames) in (2, 3), (pick, frames)
        for i, f in enumerate(frames):
            shutil.copyfile(os.path.join(work, "frames", f), os.path.join(ASSETS, f"{slug}-{i}.png"))
        approved[lift_id] = len(frames)
    with open(APPROVED, "w") as f:
        json.dump(dict(sorted(approved.items())), f, indent=1)
        f.write("\n")

os.makedirs(THUMBS, exist_ok=True)
for lift_id, count in approved.items():
    slug = lift_id.removeprefix("bundled-")
    thumb(os.path.join(ASSETS, f"{slug}-{count - 1}.png"), os.path.join(THUMBS, f"{slug}.png"))
first = next(iter(sorted(approved)))
empty_thumb(os.path.join(ASSETS, f"{first.removeprefix('bundled-')}-0.png"), os.path.join(THUMBS, "_empty.png"))

lines = [
    "// Generated by scripts/exercise-art/install.py from approved.json. Do not edit by hand.",
    "import type { ImageSourcePropType } from 'react-native';",
    "",
    "/** Approved exercise art: catalog id to its dot frames (start, end; three for a few lifts). */",
    "export const EXERCISE_ART: Readonly<Record<string, readonly ImageSourcePropType[]>> = {",
]
for lift_id, count in sorted(approved.items(), key=lambda kv: list(lifts).index(kv[0])):
    slug = lift_id.removeprefix("bundled-")
    lines.append(f"  '{lift_id}': [")
    lines += [f"    require('../../assets/images/exercise-art/{slug}-{i}.png')," for i in range(count)]
    lines.append("  ],")
lines += [
    "};",
    "",
    "/** Picker thumbnails: the working frame cropped square around the figure (52 pt at 3x). */",
    "export const EXERCISE_THUMBS: Readonly<Record<string, ImageSourcePropType>> = {",
]
for lift_id in sorted(approved, key=lambda i: list(lifts).index(i)):
    slug = lift_id.removeprefix("bundled-")
    lines.append(f"  '{lift_id}': require('../../assets/images/exercise-art/thumbs/{slug}.png'),")
lines += [
    "};",
    "",
    "/** The bare dot grid, for picker rows without art. */",
    "export const EXERCISE_THUMB_EMPTY: ImageSourcePropType = require('../../assets/images/exercise-art/thumbs/_empty.png');",
    "",
]
open(MANIFEST, "w").write("\n".join(lines))
print(f"{len(approved)} lifts in the manifest")
